name: CI

on:
  push:
    branches:
      - main
      - 'feat/*'

# defaults:
#   run:
#     shell: bash

# env:
#   OS: ubuntu-20.04

jobs:
  lint:
    name: Lint the project
    runs-on: ubuntu-20.04
    # container:
    #   image: ghcr.io/datarisk-io/datapi/ci-cd:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      # - name: Install Fantomas
      #   run: dotnet tool install -g fantomas

      - name: Run `fantomas` to lint the project
        continue-on-error: false
        # run: fantomas --check .
        run: echo "Linting project"

  test:
    name: Run tests
    needs: lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore src/myfsharpapp
          dotnet restore tests/myfsharpapp.test

      - name: Run Tests
        run: |
          dotnet test tests/myfsharpapp.test

  build:
    name: Build project
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build src/myfsharpapp

  docker:
    name: Docker
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        # runs for any branch other than main
        if: github.event_name == 'push' && github.ref != 'refs/heads/main'
        run: ./scripts/build.sh build

      - name: Build and Push Docker image
        # runs only in main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: ./scripts/build.sh
